/**
 * Add middlewares and add routes
 */

import express from 'express'
import cookieParser from 'cookie-parser'
import cors from 'cors'
// Swagger
import swaggerUI from 'swagger-ui-express'
import swaggerJsDoc from 'swagger-jsdoc'
import { options } from './config/swagger/swaggerOptions'

// import taskRoutes from './routes/tasks.routes'
import helmet from 'helmet'
import logger from './config/logger/morgan'
import compression from 'compression'

const app = express()

app.set('port', process.env.PORT || 8080)

// Middlewares

app.use(compression())
app.disable('x-powered-by')
app.use(
  helmet({
    contentSecurityPolicy: false,
    dnsPrefetchControl: false,
    ieNoOpen: false,
    referrerPolicy: false,
    xssFilter: false,
  })
)
app.use(cookieParser())
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(
  cors({
    origin: ['https://www.phynanx.com', 'http://localhost:3000'],
    credentials: true,
  })
)
app.use(logger)

// options for swagger

const specs = swaggerJsDoc(options)

const optionsUI = {
  customCss: '.swagger-ui .topbar { display: none }',
  customSiteTitle: 'Phynanx API',
  // customfavIcon: '/assets/favicon.ico',
}

// Routes
import rateLimit from 'express-rate-limit'

const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 300, // Limit each IP to 300 requests per `window` (here, per 15 minutes)
  message: 'Too many requests',
  standardHeaders: true, // Return rate limit info in the `RateLimit-*` headers
  legacyHeaders: false, // Disable the `X-RateLimit-*` headers
})

// Apply the rate limiting middleware to API calls only
app.use('/api', apiLimiter)

import routesAccount from './api/v1/routes/account/generatorAPI.route'
// route for generating api Keys
app.use('/api/v1/', routesAccount)

import routesParts from './api/v1/routes/partsFoyer/nombreParts.route'
// route for generating api Keys
app.use('/api/v1/', routesParts)

//route for documentation generated by Swagger
app.use('/docs', swaggerUI.serve, swaggerUI.setup(specs, optionsUI))

export default app
